---
title: Arquitectura Hexagonal - Módulo ChequeraSerie (v4.3.0)
---

classDiagram
    direction TB

    namespace domain {
        class ChequeraSerie {
            +Long chequeraSerieId
            +Integer facultadId
            +Integer tipoChequeraId
            +Long chequeraSerieCtacteId
            +Integer productoId
            +BigDecimal personaId
            +Integer documentoId
            +String alternativaId
            +Integer lectivoId
            +Integer arancelTipoId
            +Integer cursoId
            +Byte asentado
            +Integer geograficaId
            +OffsetDateTime fecha
            +Integer cuotasPagadas
            +String observaciones
            +Byte algoPagado
            +Integer tipoImpresionId
            +Byte flagPayperTic
            +Integer usuarioId
            +Byte enviado
            +Byte retenida
            +Long version
            +Integer hpum
            +BigDecimal becaPorcentaje
            +String becaResolucion
            +OffsetDateTime becaFecha
            +Integer becaUserId
            +getPersonaKey() String
            +getFacultadKey() String
            +jsonify() String
        }

        class ChequeraSerieRepository {
            << interface >>
            +findAllByPersonaIdAndDocumentoId(BigDecimal, Integer, Sort) List~ChequeraSerie~
            +findAllByFacultadIdAndChequeraSerieId(Integer, Long, Sort) List~ChequeraSerie~
            +findAllByPersonaIdAndDocumentoIdAndLectivoIdAndFacultadId(BigDecimal, Integer, Integer, Integer) List~ChequeraSerie~
            +findAllByLectivoIdAndFacultadId(Integer, Integer) List~ChequeraSerie~
            +findAllByFacultadIdAndLectivoIdAndGeograficaId(Integer, Integer, Integer) List~ChequeraSerie~
            +findAllByLectivoIdAndFacultadIdAndPersonaId(Integer, Integer, BigDecimal) List~ChequeraSerie~
            +findAllByLectivoIdAndFacultadIdAndGeograficaId(Integer, Integer, Integer) List~ChequeraSerie~
            +findAllByGeograficaIdAndFacultadIdInAndLectivoIdIn(Integer, List~Integer~, List~Integer~) List~ChequeraSerie~
            +findAllByFacultadIdAndLectivoIdAndTipoChequeraId(Integer, Integer, Integer) List~ChequeraSerie~
            +findAllByPersonaIdAndDocumentoIdAndFacultadId(BigDecimal, Integer, Integer) List~ChequeraSerie~
            +findAllByPersonaIdAndDocumentoIdAndFacultadIdAndLectivoId(BigDecimal, Integer, Integer, Integer) List~ChequeraSerie~
            +findAllByFacultadIdAndLectivoIdAndGeograficaIdAndPersonaIdIn(Integer, Integer, Integer, List~BigDecimal~) List~ChequeraSerie~
            +findAllByPersonaIdAndDocumentoIdAndLectivoId(BigDecimal, Integer, Integer) List~ChequeraSerie~
            +findFirstByFacultadIdAndPersonaIdAndDocumentoIdAndLectivoId(Integer, BigDecimal, Integer, Integer) Optional~ChequeraSerie~
            +findByFacultadIdAndTipoChequeraIdAndChequeraSerieId(Integer, Integer, Long) Optional~ChequeraSerie~
            +findByChequeraId(Long) Optional~ChequeraSerie~
            +findFirstByPersonaIdAndDocumentoIdAndFacultadIdAndLectivoIdAndGeograficaId(BigDecimal, Integer, Integer, Integer, Integer) Optional~ChequeraSerie~
            +findFirstByPersonaIdAndDocumentoIdAndFacultadIdAndLectivoIdAndGeograficaIdAndTipoChequeraId(BigDecimal, Integer, Integer, Integer, Integer, Integer) Optional~ChequeraSerie~
            +findFirstByPersonaIdAndDocumentoIdAndFacultadIdAndLectivoIdAndGeograficaIdAndTipoChequeraIdIn(BigDecimal, Integer, Integer, Integer, Integer, List~Integer~) Optional~ChequeraSerie~
            +findFirstByPersonaIdAndDocumentoIdAndFacultadIdAndTipoChequeraIdIn(BigDecimal, Integer, Integer, List~Integer~, Sort) Optional~ChequeraSerie~
            +findAllByPersonaIdAndDocumentoIdAndFacultadIdAndTipoChequeraIdIn(BigDecimal, Integer, Integer, List~Integer~, Sort) List~ChequeraSerie~
            +deleteAllByFacultadIdAndTipoChequeraIdAndChequeraSerieId(Integer, Integer, Long)
            +findAllFacultadSedeByLectivo(Integer) List~FacultadSedeChequeraDto~
            +save(ChequeraSerie) ChequeraSerie
        }
    }

    namespace application {
        class ChequeraSerieService {
            -CreateChequeraSerieUseCase createUseCase
            -DeleteChequeraSerieUseCase deleteUseCase
            -GetChequeraSerieAltasUseCase altasUseCase
            -GetChequeraSerieByCbuOrVisaUseCase cbuOrVisaUseCase
            -GetChequeraSerieByFacultadUseCase byFacultadUseCase
            -GetChequeraSerieByIdUseCase byIdUseCase
            -GetChequeraSerieByNumberUseCase byNumberUseCase
            -GetChequeraSerieByPersonaUseCase byPersonaUseCase
            -GetChequeraSerieByUniqueUseCase byUniqueUseCase
            -GetChequeraSerieIncompletasUseCase incompletasUseCase
            -GetChequeraSerieSpecialQueriesUseCase specialUseCase
            -GetResumenLectivoUseCase resumenUseCase
            -MarkSentUseCase markSentUseCase
            -SetPayPerTicUseCase payPerTicUseCase
            -UpdateChequeraSerieUseCase updateUseCase
        }

    }
    namespace application_usecases {
            class CreateChequeraSerieUseCaseImpl
            class DeleteChequeraSerieUseCaseImpl
            class GetChequeraSerieAltasUseCaseImpl
            class GetChequeraSerieByCbuOrVisaUseCaseImpl
            class GetChequeraSerieByFacultadUseCaseImpl
            class GetChequeraSerieByIdUseCaseImpl
            class GetChequeraSerieByNumberUseCaseImpl
            class GetChequeraSerieByPersonaUseCaseImpl
            class GetChequeraSerieByUniqueUseCaseImpl
            class GetChequeraSerieIncompletasUseCaseImpl
            class GetChequeraSerieSpecialQueriesUseCaseImpl
            class GetResumenLectivoUseCaseImpl
            class MarkSentUseCaseImpl
            class SetPayPerTicUseCaseImpl
            class UpdateChequeraSerieUseCaseImpl
            class FindPreuniversitarioFromDatosGuaraniUseCaseImpl
    }
    namespace application {

        class ChequeraSerieException
        class FindPreuniversitarioFromDatosGuaraniUseCase {
            << interface >>
            +find(BigDecimal, Integer, Integer, Integer, Integer) ChequeraSerie
        }
    }

    namespace infrastructure_persistence {
            class ChequeraSerieEntity {
                +Long chequeraSerieId
                +Integer facultadId
                +Integer tipoChequeraId
                +...
                +jsonify() String
            }

            class JpaChequeraSerieRepository {
                << JpaRepository >>
            }

            class JpaChequeraSerieRepositoryAdapter {
                -JpaChequeraSerieRepository repository
                -ChequeraSerieMapper mapper
                implements ChequeraSerieRepository
            }

            class ChequeraSerieMapper {
                +toDomainModel(ChequeraSerieEntity) ChequeraSerie
                +toEntity(ChequeraSerie) ChequeraSerieEntity
            }
    }
    namespace infrastructure_web {
            class ChequeraSerieController {
                -ChequeraSerieService service
                -ChequeraSerieDtoMapper dtoMapper
            }

            class ChequeraSerieRequest
            class ChequeraSerieResponse
            class ChequeraSerieDtoMapper {
                +toDomain(ChequeraSerieRequest) ChequeraSerie
                +toResponse(ChequeraSerie) ChequeraSerieResponse
            }
    }

    namespace view {
        class ChequeraSerieAltaService {
            +findAllByLectivoIdAndFacultadIdAndGeograficaId(Integer, Integer, Integer) List~ChequeraSerieAlta~
        }

        class ChequeraSerieAltaFullService {
            +findAllByLectivoIdAndFacultadIdAndGeograficaIdAndTipoChequeraId(Integer, Integer, Integer, Integer, OffsetDateTime, ChequeraCuotaService) List~ChequeraSerieAltaFull~
        }

        class ChequeraIncompletaService {
            +findAllByLectivoIdAndFacultadIdAndGeograficaIdAndClaseChequeraId(Integer, Integer, Integer, Integer) List~ChequeraIncompleta~
        }

        class ChequeraKeyService
        class DebitoService

        class ChequeraIncompletaRepository {
            << JpaRepository >>
            +findAllByLectivoIdAndFacultadIdAndGeograficaIdAndTipoChequeraClaseChequeraId(Integer, Integer, Integer, Integer, Sort) List~ChequeraIncompleta~
        }

        class ChequeraIncompleta {
            +Long chequeraId
            +Integer facultadId
            +Integer tipoChequeraId
            +Long chequeraSerieId
            +BigDecimal personaId
            +Integer documentoId
            +Integer lectivoId
            +Integer geograficaId
            +TipoChequeraEntity tipoChequera
        }
    }

    ChequeraSerieService --> CreateChequeraSerieUseCase : uses
    ChequeraSerieService --> DeleteChequeraSerieUseCase : uses
    ChequeraSerieService --> GetChequeraSerieAltasUseCase : uses
    ChequeraSerieService --> GetChequeraSerieByCbuOrVisaUseCase : uses
    ChequeraSerieService --> GetChequeraSerieByFacultadUseCase : uses
    ChequeraSerieService --> GetChequeraSerieByIdUseCase : uses
    ChequeraSerieService --> GetChequeraSerieByNumberUseCase : uses
    ChequeraSerieService --> GetChequeraSerieByPersonaUseCase : uses
    ChequeraSerieService --> GetChequeraSerieByUniqueUseCase : uses
    ChequeraSerieService --> GetChequeraSerieIncompletasUseCase : uses
    ChequeraSerieService --> GetChequeraSerieSpecialQueriesUseCase : uses
    ChequeraSerieService --> GetResumenLectivoUseCase : uses
    ChequeraSerieService --> MarkSentUseCase : uses
    ChequeraSerieService --> SetPayPerTicUseCase : uses
    ChequeraSerieService --> UpdateChequeraSerieUseCase : uses

    CreateChequeraSerieUseCaseImpl ..|> CreateChequeraSerieUseCase
    DeleteChequeraSerieUseCaseImpl ..|> DeleteChequeraSerieUseCase
    GetChequeraSerieAltasUseCaseImpl ..|> GetChequeraSerieAltasUseCase
    GetChequeraSerieByCbuOrVisaUseCaseImpl ..|> GetChequeraSerieByCbuOrVisaUseCase
    GetChequeraSerieByFacultadUseCaseImpl ..|> GetChequeraSerieByFacultadUseCase
    GetChequeraSerieByIdUseCaseImpl ..|> GetChequeraSerieByIdUseCase
    GetChequeraSerieByNumberUseCaseImpl ..|> GetChequeraSerieByNumberUseCase
    GetChequeraSerieByPersonaUseCaseImpl ..|> GetChequeraSerieByPersonaUseCase
    GetChequeraSerieByUniqueUseCaseImpl ..|> GetChequeraSerieByUniqueUseCase
    GetChequeraSerieIncompletasUseCaseImpl ..|> GetChequeraSerieIncompletasUseCase
    GetChequeraSerieSpecialQueriesUseCaseImpl ..|> GetChequeraSerieSpecialQueriesUseCase
    GetResumenLectivoUseCaseImpl ..|> GetResumenLectivoUseCase
    MarkSentUseCaseImpl ..|> MarkSentUseCase
    SetPayPerTicUseCaseImpl ..|> SetPayPerTicUseCase
    UpdateChequeraSerieUseCaseImpl ..|> UpdateChequeraSerieUseCase
    FindPreuniversitarioFromDatosGuaraniUseCaseImpl ..|> FindPreuniversitarioFromDatosGuaraniUseCase

    CreateChequeraSerieUseCaseImpl --> ChequeraSerieRepository : uses
    DeleteChequeraSerieUseCaseImpl --> ChequeraSerieRepository : uses
    GetChequeraSerieAltasUseCaseImpl --> ChequeraSerieAltaService : uses
    GetChequeraSerieAltasUseCaseImpl --> ChequeraSerieAltaFullService : uses
    GetChequeraSerieByCbuOrVisaUseCaseImpl --> DebitoService : uses
    GetChequeraSerieByCbuOrVisaUseCaseImpl --> ChequeraKeyService : uses
    GetChequeraSerieByFacultadUseCaseImpl --> ChequeraSerieRepository : uses
    GetChequeraSerieByIdUseCaseImpl --> ChequeraSerieRepository : uses
    GetChequeraSerieByNumberUseCaseImpl --> ChequeraSerieRepository : uses
    GetChequeraSerieByPersonaUseCaseImpl --> ChequeraSerieRepository : uses
    GetChequeraSerieByUniqueUseCaseImpl --> ChequeraSerieRepository : uses
    GetChequeraSerieIncompletasUseCaseImpl --> ChequeraIncompletaService : uses
    ChequeraIncompletaService --> ChequeraIncompletaRepository : uses
    ChequeraIncompletaRepository --> ChequeraIncompleta : view
    GetChequeraSerieSpecialQueriesUseCaseImpl --> ChequeraSerieRepository : uses
    GetResumenLectivoUseCaseImpl --> ChequeraSerieRepository : uses
    MarkSentUseCaseImpl --> ChequeraSerieRepository : uses
    SetPayPerTicUseCaseImpl --> ChequeraSerieRepository : uses
    UpdateChequeraSerieUseCaseImpl --> ChequeraSerieRepository : uses

    JpaChequeraSerieRepositoryAdapter ..|> ChequeraSerieRepository : implements
    JpaChequeraSerieRepositoryAdapter --> JpaChequeraSerieRepository : uses
    JpaChequeraSerieRepositoryAdapter --> ChequeraSerieMapper : uses

    ChequeraSerieMapper --> ChequeraSerie : maps
    ChequeraSerieMapper --> ChequeraSerieEntity : maps
    JpaChequeraSerieRepository --> ChequeraSerieEntity : persists

    ChequeraSerieController --> ChequeraSerieService : calls
    ChequeraSerieController --> ChequeraSerieDtoMapper : uses
    ChequeraSerieDtoMapper --> ChequeraSerie : maps
    ChequeraSerieDtoMapper --> ChequeraSerieResponse : maps
