---
title: Consulta de Artículos (Arquitectura Hexagonal)
---
sequenceDiagram
    participant C as Cliente
    participant Ctrl as ArticuloController
    participant S as ArticuloService
    participant R as JpaArticuloRepository
    participant DB as BaseDeDatos
    C->>Ctrl: GET /articulo/
    Ctrl->>S: findAll()
    S->>R: findAll()
    R->>DB: SELECT * FROM articulos
    DB-->>R: lista ArticuloEntity
    R-->>S: List~ArticuloEntity~
    S-->>Ctrl: List~ArticuloEntity~
    Ctrl-->>C: ResponseEntity~List~ArticuloEntity~~ 200 OK
