name: Generate Documentation

on:
  pull_request:
    types: [opened, synchronize, reopened]
  push:
    branches: [main]

permissions:
  contents: write
  pages: write
  id-token: write
  issues: read
  pull-requests: read

jobs:
  generate-docs:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up JDK 24
        uses: actions/setup-java@v4
        with:
          java-version: '24'
          distribution: 'temurin'
          cache: maven

      - name: Generate Dependency Tree
        run: mvn dependency:tree -DoutputFile=docs/dependency-tree.txt

      - name: Fetch GitHub Data
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          curl -s -H "Authorization: token $GITHUB_TOKEN" "https://api.github.com/repos/${{ github.repository }}/milestones" > docs/milestones.json
          curl -s -H "Authorization: token $GITHUB_TOKEN" "https://api.github.com/repos/${{ github.repository }}/issues?state=all&per_page=100" > docs/issues.json
          curl -s -H "Authorization: token $GITHUB_TOKEN" "https://api.github.com/repos/${{ github.repository }}/pulls?state=all&per_page=100" > docs/prs.json

      - name: Generate Wiki Content
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config --global user.email "actions@github.com"
          git config --global user.name "GitHub Actions"
          
          git clone https://github.com/${{ github.repository }}.wiki.git wiki || {
              mkdir wiki
              cd wiki
              git init
              git remote add origin https://github.com/${{ github.repository }}.wiki.git
              git checkout -b master
              cd ..
          }
          
          cd wiki
          
          # Create a simple Home.md as a portal
          cat > Home.md << EOF
          # 游늶 Wiki del Proyecto UM.tesoreria.core-service

          Esta wiki sirve como un portal de acceso r치pido a los recursos m치s importantes del proyecto.

          Toda la **documentaci칩n detallada, interactiva y actualizada** se encuentra en nuestro sitio de **GitHub Pages**.

          ## 俱뫮잺 [Acceder a la Documentaci칩n Principal](https://$(echo ${{ github.repository_owner }} | tr '[:upper:]' '[:lower:]').github.io/$(echo ${{ github.repository }} | cut -d'/' -f2)/)

          ---

          ### Accesos Directos a GitHub

          *   **[Issues](https://github.com/${{ github.repository }}/issues)**: Ver todos los issues, abiertos y cerrados.
          *   **[Pull Requests](https://github.com/${{ github.repository }}/pulls)**: Ver todos los Pull Requests.
          *   **[Milestones](https://github.com/${{ github.repository }}/milestones)**: Ver el progreso de los hitos del proyecto.
          EOF

          # Clean up old, now-unused wiki pages
          rm -f "Estado-del-Proyecto.md" "Pull-Requests.md"

          git add .
          git commit -m "Update wiki to act as a portal to the main documentation" || echo "No changes to commit"
          
          if [[ "${{ github.event.pull_request.head.repo.full_name }}" == "${{ github.repository }}" ]] || [[ "${{ github.event_name }}" == "push" ]]; then
            git push --set-upstream https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}.wiki.git master
          fi

      - name: Upload artifacts
        uses: actions/upload-pages-artifact@v3
        with:
          path: docs

  deploy-pages:
    needs: generate-docs
    runs-on: ubuntu-latest
    if: github.event_name == 'push' || (github.event_name == 'pull_request' && github.event.action == 'closed' && github.event.pull_request.merged == true)
    permissions:
      pages: write
      id-token: write
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
